<?php

/*
 * CURSEWORK mini-Framework
 * 2020-2021 By Rikz.
 * https://github.com/Amrikz/CURSEwork
*/


/*
 * Define project root directory
 */
define('PROJECT_DIR', __DIR__);

/*
 * Override Server php.ini conf for startup errors
 */
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);

/*
 * Init modules in one place
 */
require_once join(DIRECTORY_SEPARATOR,['App','Lib','Includes','init.php']);

/*
 * Routes middleware
 */
require_once join(DIRECTORY_SEPARATOR,['App','Lib','Middleware','RouteMiddleware.php']);



/*
 * GLOBAL_TODO
 * TODO: Move index.php to /Public.
 * TODO: Make js/css/img directories autogenerated.
 * TODO: Migrations. With models integration.
 * TODO: Tests. Unit Auto-Tests for each class.
 * TODO: CORS. Somehow test and make.
 *
 * IN_PROGRESS
 ~ TODO: Get rid of mess. Clean all.
 ~ TODO: MIDDLEWARES. Work on it.
 ~ TODO: Make Messaging/Logging systems.
 ~ TODO: Make Security transfer classes (repository) and wrapper pipelines.
 ~ TODO: Routeworks. Make routes vary get/post. Make api.php links start with /api.
 *
 * DONE
 + TODO: Handlers. Error and exception handlers.
 + TODO: Add Helper functions.
 + TODO: Migrate DB from Mysqli to PDO.
 + TODO: Refactor Config classes AND move them to /Config.
 + TODO: Make Normal Models/Controllers system with BaseModel class and Model interface.
 + TODO: Make "easy for use" Models call to Database.
 + TODO: Rename vendor and its namespace to lib.
*/